included:
  - Movies
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
 - accessibility_label_for_image
 - accessibility_trait_for_button
 - anonymous_argument_in_multiline_closure
 - anyobject_protocol
 - array_init
 - attributes
 - balanced_xctest_lifecycle
 - capture_variable
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - comma_inheritance
 - conditional_returns_on_newline
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - convenience_type
 - discarded_notification_center_observer
 - discouraged_assert
 - discouraged_none_name
 - discouraged_object_literal
 - discouraged_optional_boolean
 - empty_collection_literal
 - empty_count
 - empty_string
 - empty_xctest_method
 - enum_case_associated_values_count
 - expiring_todo
 - explicit_init
 - explicit_self
 - extension_access_modifier
 - fallthrough
 - fatal_error_message
 - file_header
 - file_name_no_space
 - first_where
 - flatmap_over_map_reduce
 - function_default_parameter_at_end
 - ibinspectable_in_extension
 - identical_operands
 - implicit_return
 - indentation_width
 - joined_default_parameter
 - last_where
 - legacy_multiple
 - legacy_objc_type
 - let_var_whitespace
 - literal_expression_end_indentation
 - local_doc_comment
 - lower_acl_than_parent
 - missing_docs
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - nimble_operator
 - no_magic_numbers
 - nslocalizedstring_key
 - nslocalizedstring_require_bundle
 - number_separator
 - object_literal
 - operator_usage_whitespace
 - optional_enum_case_matching
 - overridden_super_call
 - override_in_extension
 - pattern_matching_keywords
 - prefer_nimble
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - private_subject
 - prohibited_super_call
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - raw_value_for_camel_cased_codable_enum
 - reduce_into
 - redundant_nil_coalescing
 - redundant_type_annotation
 - required_enum_case
 - return_value_from_void_function
 - self_binding
 - shorthand_optional_binding
 - single_test_class
 - sorted_first_last
 - sorted_imports
 - static_operator
 - strict_fileprivate
 - switch_case_on_newline
 - test_case_accessibility
 - toggle_bool
 - trailing_closure
 - type_contents_order
 - typesafe_array_init
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 - unused_declaration
 - unused_import
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces
 - weak_delegate
 - xct_specific_matcher
 - yoda_condition

custom_rules:
  # Wrong:
  #  func abc(a: String, b: String) { }
  # Wrong:
  #   func abc(a: String, b: String) { }
  # Correct:
  #    func abc(a: String, b: String) { }
  og_indentation:
    name: Indentation
    regex: >-
      (?#
      )^\h{1,3}\H|(?#
      )^\h{5,7}\H|(?#
      )^\h{9,11}\H|(?#
      )^\h{13,15}\H|(?#
      )^\h{17,19}\H|(?#
      )^\h{21,23}\H|(?#
      )^\h{25,}?\H
    match_kinds:
      - argument
      - attribute.builtin
      - attribute.id
      - comment
      - comment.mark
      - comment.url
      - identifier
      - keyword
      - number
      - objectliteral
      - parameter
      - placeholder
      - typeidentifier
    message: >-
      Number of initial line whitespaces should be 0 or
      divisible by 4 and shouldn't be greater than 24.
  # Wrong:
  #    case BMP  = "bmp"
  #    case TIFF = "tiff"
  # Correct:
  #    case BMP = "bmp"
  #    case TIFF = "tiff"
  # Known issues:
  # Following line is linted successfully for some reason:
  #    let blue = CGFloat(  (  hex & 0x0000FF) >> 0)  /  0xFF
  # It looks like it has something to do with parentheses and slashes,
  # maybe it's a side effect of other rules.

  og_duplicated_spaces:
    name: Duplicated spaces
    regex: \S\h{2,}?\S
    match_kinds:
      - argument
      - identifier
      - keyword
      - number
      - objectliteral
      - parameter
      - placeholder
      - typeidentifier
    message: >-
      There should be no multiple consecutive spaces in a line
      (except indentation spaces in a beginning of a line).

  # Wrong:
  #    override public
  # Correct:
  #    public override
  og_acl_first:
    name: ACL First
    regex: (^|\h)\w+\h+(open|public|internal|fileprivate|private)(?!\(set\))
    match_kinds:
      - attribute.builtin
    message: >-
     Access Control Level keywords should precede other modifiers.

file_length: 300
function_body_length: 50
function_parameter_count: 5
generic_type_name:
  min_length: 0
  max_length: 20
identifier_name:
  min_length: 0
  max_length: 40
large_tuple: 5
line_length: 120
number_separator:
  minimum_length: 5
trailing_comma:
  severity: error
  mandatory_comma: true
cyclomatic_complexity: 10
type_name:
  min_length: 0
  max_length: 50

function_body_length: 60
type_body_length: 400

unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder # we can't detect uses of string interpolation of swift syntax nodes
